# Generated by Django 5.0.6 on 2024-06-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(default='online-shopping-background-website-mobile-app_269039-166.jpg', upload_to='carousel/'),
        ),
    ]
