# Generated by Django 5.0.6 on 2024-06-23 04:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
