# Generated by Django 5.0.6 on 2024-08-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_payment_order_payment_id_order_uuid_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='order.order'),
        ),
    ]
