# Generated by Django 5.0.6 on 2024-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_signature',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
