# Generated by Django 5.0.6 on 2024-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_carousel_description_alter_carousel_title'),
        ('cart', '0001_initial'),
        ('product', '0004_brand_category_remove_product_category_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
