# Generated by Django 5.0.3 on 2024-05-19 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderstatus'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='charges',
            field=models.IntegerField(default=0),
        ),
    ]
