# Generated by Django 5.0.6 on 2024-08-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(default='0', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.orderstatus'),
        ),
    ]
